FROM node:alpine
WORKDIR /usr/src/app
ENV PATH /app/node_modules/.bin:$PATH
COPY package*.json ./
RUN npm install
RUN npm install -g @angular/cli@8.3.23
COPY . .
EXPOSE 4200
CMD ng serve --host 0.0.0.0